import { getDb } from "../api/queries/connection";
import { services, blogPosts, testimonials } from "./schema";

async function seed() {
  const db = getDb();
  console.log("Seeding database...");

  // ── Seed Services ──────────────────────────────────
  await db.insert(services).values([
    {
      slug: "research-paper-writing",
      titleEn: "Research Paper Writing",
      titleHi: "रिसर्च पेपर राइटिंग",
      shortDescEn: "Get professionally written research papers for SCI, Scopus, and UGC CARE indexed journals with original methodology and data analysis.",
      shortDescHi: "SCI, Scopus और UGC CARE जर्नल के लिए पेशेवर रूप से लिखे गए रिसर्च पेपर प्राप्त करें।",
      fullDescEn: "Our expert writers craft high-quality research papers tailored for SCI, Scopus, UGC CARE, and ABDC indexed journals. We ensure original methodology, proper data analysis, plagiarism-free content, and compliance with journal guidelines. From conceptualization to final submission-ready manuscript, we handle every detail with academic precision.",
      fullDescHi: "हमारे विशेषज्ञ लेखक SCI, Scopus, UGC CARE और ABDC अनुक्रमित जर्नल के लिए उच्च गुणवत्ता वाले रिसर्च पेपर तैयार करते हैं।",
      icon: "FileText",
      sortOrder: 1,
    },
    {
      slug: "review-paper-writing",
      titleEn: "Review Paper Writing",
      titleHi: "रिव्यू पेपर राइटिंग",
      shortDescEn: "Comprehensive systematic and narrative review papers with extensive literature analysis for top-tier publications.",
      shortDescHi: "शीर्ष-स्तरीय प्रकाशनों के लिए व्यापक साहित्य विश्लेषण के साथ सिस्टमैटिक और नैरेटिव रिव्यू पेपर।",
      fullDescEn: "We specialize in crafting systematic reviews, narrative reviews, scoping reviews, and meta-analyses. Our team conducts comprehensive literature searches across multiple databases (Scopus, Web of Science, PubMed, IEEE), synthesizes findings using PRISMA guidelines, and delivers publication-ready manuscripts with critical analysis and future research directions.",
      fullDescHi: "हम सिस्टमैटिक रिव्यू, नैरेटिव रिव्यू, स्कोपिंग रिव्यू और मेटा-एनालिसिस तैयार करने में विशेषज्ञ हैं।",
      icon: "BookOpen",
      sortOrder: 2,
    },
    {
      slug: "thesis-writing",
      titleEn: "Thesis & Dissertation Writing",
      titleHi: "थीसिस और डिसर्टेशन राइटिंग",
      shortDescEn: "Complete PhD thesis, Master's dissertation, and M.Phil thesis writing with chapter-wise expert guidance.",
      shortDescHi: "पीएचडी थीसिस, मास्टर डिसर्टेशन और एम.फिल थीसIS लेखन पूर्ण अध्याय-वार मार्गदर्शन के साथ।",
      fullDescEn: "From proposal to final viva, we provide end-to-end thesis writing services. Our experts assist with literature review, research methodology design, data collection and analysis, results interpretation, and discussion writing. We ensure your thesis meets university guidelines and international academic standards. Chapter-wise delivery with unlimited revisions.",
      fullDescHi: "प्रस्ताव से अंतिम वाइवा तक, हम अंत-से-अंत थीसिस लेखन सेवाएं प्रदान करते हैं।",
      icon: "GraduationCap",
      sortOrder: 3,
    },
    {
      slug: "methodology-design",
      titleEn: "Research Methodology Design",
      titleHi: "रिसर्च मेथडोलॉजी डिज़ाइन",
      shortDescEn: "Expert assistance in designing quantitative, qualitative, and mixed-method research frameworks.",
      shortDescHi: "मात्रात्मक, गुणात्मक और मिश्रित-विधि अनुसंधान ढांचे को डिजाइन करने में विशेषज्ञ सहायता।",
      fullDescEn: "We help researchers design robust research methodologies including experimental designs, survey instruments, case study protocols, ethnographic approaches, and mixed-method frameworks. Our team ensures methodological rigor, validity, reliability, and ethical compliance in every research design.",
      fullDescHi: "हम शोधकर्ताओं को मजबूत शोध पद्धतियां डिजाइन करने में मदद करते हैं।",
      icon: "Settings",
      sortOrder: 4,
    },
    {
      slug: "conceptual-model",
      titleEn: "Conceptual Framework Development",
      titleHi: "कांसेप्चुअल फ्रेमवर्क डेवलपमेंट",
      shortDescEn: "Build strong theoretical frameworks with hypothesis development and structural equation modeling.",
      shortDescHi: "हाइपोथीसिस डेवलपमेंट और स्ट्रक्चरल इक्वेशन मॉडलिंग के साथ मजबूत सैद्धांतिक फ्रेमवर्क बनाएं।",
      fullDescEn: "Our experts develop comprehensive conceptual frameworks grounded in established theories. We assist with hypothesis formulation, variable identification, mediating and moderating variable analysis, and structural equation modeling (SEM) using AMOS, SmartPLS, and SPSS. Visual framework diagrams included.",
      fullDescHi: "हमारे विशेषज्ञ स्थापित सिद्धांतों में आधारित व्यापक कल्पनात्मक ढांचे विकसित करते हैं।",
      icon: "Network",
      sortOrder: 5,
    },
    {
      slug: "peer-review",
      titleEn: "Peer Review & Paper Improvement",
      titleHi: "पीयर रिव्यू और पेपर इंप्रूवमेंट",
      shortDescEn: "Expert peer review service to improve paper quality before journal submission.",
      shortDescHi: "जर्नल सबमिशन से पहले पेपर की गुणवत्ता में सुधार के लिए विशेषज्ञ पीयर रिव्यू सेवा।",
      fullDescEn: "Get your paper reviewed by subject matter experts before submission. We provide detailed feedback on research design, methodology, data analysis, writing quality, and journal fit. Our review process includes language editing, formatting according to journal guidelines, and addressing potential reviewer concerns.",
      fullDescHi: "सबमिशन से पहले विषय विशेषज्ञों द्वारा अपने पेपर की समीक्षा करवाएं।",
      icon: "Eye",
      sortOrder: 6,
    },
    {
      slug: "plagiarism-removal",
      titleEn: "Plagiarism & AI Detection Removal",
      titleHi: "प्लagiarism और AI डिटेक्शन रिमूवल",
      shortDescEn: "Advanced plagiarism removal and AI content humanization for 100% originality.",
      shortDescHi: "100% मौलिकता के लिए एडवांस्ड प्लagiarism रिमूवल और AI कंटेंट ह्यूमनाइजेशन।",
      fullDescEn: "We use advanced techniques to reduce plagiarism below 10% (Turnitin, iThenticate) and humanize AI-generated content to bypass AI detection tools (GPTZero, Copyleaks, ZeroGPT). Our experts rewrite content while maintaining academic integrity, proper citations, and the original meaning of your research.",
      fullDescHi: "हम Turnitin, iThenticate में प्लagiarism 10% से कम करने और AI डिटेक्शन टूल्स को बायपास करने के लिए उन्नत तकनीकों का उपयोग करते हैं।",
      icon: "ShieldCheck",
      sortOrder: 7,
    },
    {
      slug: "publication-support",
      titleEn: "Journal Publication Support",
      titleHi: "जर्नल पब्लिकेशन सपोर्ट",
      shortDescEn: "End-to-end support for publishing in SCI, Scopus, Web of Science, and UGC CARE journals.",
      shortDescHi: "SCI, Scopus, Web of Science और UGC CARE जर्नल में प्रकाशन के लिए अंत-से-अंत सहायता।",
      fullDescEn: "We provide complete publication support including journal selection (SCI, Scopus, WoS, UGC CARE, ABDC), manuscript formatting, cover letter writing, response to reviewer comments, and resubmission support. Our team has a proven track record of successful publications in Q1 and Q2 journals across all disciplines.",
      fullDescHi: "हम SCI, Scopus, WoS, UGC CARE, ABDC में जर्नल चयन, मैन्युस्क्रिप्ट फॉर्मेटिंग, कवर लेटर लेखन सहित पूर्ण प्रकाशन सहायता प्रदान करते हैं।",
      icon: "Globe",
      sortOrder: 8,
    },
  ]);
  console.log("Services seeded.");

  // ── Seed Blog Posts ────────────────────────────────
  await db.insert(blogPosts).values([
    {
      slug: "ai-tools-research-paper-writing",
      titleEn: "Top 15 AI Tools That Help in Research Paper Writing",
      titleHi: "रिसर्च पेपर राइटिंग में मदद करने वाले टॉप 15 AI टूल्स",
      excerptEn: "Discover the best AI-powered tools that can accelerate your research process, from literature review to manuscript preparation.",
      excerptHi: "साहित्य समीक्षा से लेकर पांडुलिपि तैयारी तक अपने शोध प्रक्रिया को तेज करने वाले सर्वश्रेष्ठ AI-संचालित उपकरणों की खोज करें।",
      contentEn: "AI tools have revolutionized academic research. This comprehensive guide covers tools like Consensus for AI-powered search, Elicit for research analysis, ChatGPT for drafting, Grammarly for editing, Scite for citation analysis, ResearchRabbit for literature mapping, and many more. Learn how to ethically integrate AI into your research workflow while maintaining academic integrity.",
      contentHi: "AI टूल्स ने अकादमिक शोध में क्रांति ला दी है। यह व्यापक गाइड AI-संचालित खोज के लिए Consensus, शोध विश्लेषण के लिए Elicit, ड्राफ्टिंग के लिए ChatGPT जैसे टूल्स को कवर करता है।",
      category: "AI Tools",
      image: "/images/blog-ai-tools.jpg",
      tags: "AI,Research Tools,ChatGPT,Academic Writing",
      readTime: 8,
    },
    {
      slug: "publish-in-scopus-indexed-journals",
      titleEn: "How to Publish in Scopus Indexed Journals: Complete Guide",
      titleHi: "Scopus Indexed Journals में प्रकाशन कैसे करें: पूर्ण गाइड",
      excerptEn: "A step-by-step guide to getting your research published in Scopus-indexed journals with practical tips and strategies.",
      excerptHi: "व्यावहारिक सुझावों और रणनीतियों के साथ Scopus-अनुक्रमित जर्नल में अपने शोध को प्रकाशित करने के लिए चरण-दर-चरण मार्गदर्शिका।",
      contentEn: "Publishing in Scopus-indexed journals requires understanding the indexing criteria, selecting the right journal, preparing a quality manuscript, and navigating the peer review process. This guide covers everything from identifying predatory journals to writing an effective cover letter and responding to reviewer comments.",
      contentHi: "Scopus-अनुक्रमित जर्नल में प्रकाशन के लिए अनुक्रमण मानदंड को समझना, सही जर्नल चुनना, गुणवत्ता पांडुलिपि तैयार करना और पीयर रिव्यू प्रक्रिया को नेविगेट करना आवश्यक है।",
      category: "Publications",
      image: "/images/blog-scopus.jpg",
      tags: "Scopus,Publications,Journal Guide,Research",
      readTime: 10,
    },
    {
      slug: "sci-journal-publication-tips",
      titleEn: "SCI Journal Publication: Tips for Successful Acceptance",
      titleHi: "SCI जर्नल पब्लिकेशन: सफल स्वीकृति के लिए टिप्स",
      excerptEn: "Expert strategies to increase your chances of getting accepted in Science Citation Index (SCI) journals.",
      excerptHi: "साइंस साइटेशन इंडेक्स (SCI) जर्नल में स्वीकार होने की संभावना बढ़ाने के लिए विशेषज्ञ रणनीतियां।",
      contentEn: "SCI journals have the highest impact factors and stringent review processes. Learn how to target Q1 and Q2 journals, improve your manuscript's novelty and significance, ensure robust methodology, and present compelling results. Includes tips on journal selection tools like Journal Finder and Edanz.",
      contentHi: "SCI जर्नल में उच्चतम इम्पैक्ट फैक्टर और कठोर समीक्षा प्रक्रिया होती है। जानें कि Q1 और Q2 जर्नल को कैसे लक्षित करें, पांडुलिपि की नवीनता कैसे बढ़ाएं।",
      category: "Publications",
      image: "/images/blog-sci.jpg",
      tags: "SCI,Science Citation Index,Q1 Journals,Impact Factor",
      readTime: 9,
    },
    {
      slug: "write-literature-review",
      titleEn: "How to Write an Effective Literature Review",
      titleHi: "प्रभावी साहित्य समीक्षा कैसे लिखें",
      excerptEn: "Master the art of writing comprehensive literature reviews that form the backbone of any research paper.",
      excerptHi: "किसी भी रिसर्च पेपर की रीढ़ बनाने वाली व्यापक साहित्य समीक्षा लेखन की कला में महारत हासिल करें।",
      contentEn: "A literature review is not just a summary of sources. Learn systematic approaches to literature search, synthesis frameworks, thematic analysis, gap identification, and writing strategies. Covers PRISMA guidelines, citation mapping, and tools like Connected Papers and Litmaps.",
      contentHi: "साहित्य समीक्षा केवल स्रोतों का सारांश नहीं है। साहित्य खोज, संश्लेषण ढांचे, थीमैटिक विश्लेषण और गैप पहचानने के लिए व्यवस्थित दृष्टिकोण सीखें।",
      category: "Writing Guide",
      image: "/images/blog-literature.jpg",
      tags: "Literature Review,Writing Guide,Research Method",
      readTime: 7,
    },
    {
      slug: "research-methodology-types",
      titleEn: "Types of Research Methodology: A Comprehensive Overview",
      titleHi: "रिसर्च मेथडोलॉजी के प्रकार: एक व्यापक अवलोकन",
      excerptEn: "Understand quantitative, qualitative, and mixed research methods to choose the right approach for your study.",
      excerptHi: "अपने अध्ययन के लिए सही दृष्टिकोण चुनने के लिए मात्रात्मक, गुणात्मक और मिश्रित शोध विधियों को समझें।",
      contentEn: "Choosing the right methodology is crucial for research validity. This article explains experimental, correlational, descriptive, ethnographic, case study, action research, and grounded theory approaches. Includes decision frameworks and practical examples from different disciplines.",
      contentHi: "सही मेथडोलॉजी चुनना शोध वैधता के लिए महत्वपूर्ण है। यह लेख प्रयोगात्मक, सहसंबंधी, वर्णनात्मक, नृवंशविज्ञानी दृष्टिकोणों की व्याख्या करता है।",
      category: "Methodology",
      image: "/images/blog-methodology.jpg",
      tags: "Methodology,Quantitative,Qualitative,Mixed Methods",
      readTime: 8,
    },
    {
      slug: "plagiarism-removal-techniques",
      titleEn: "Effective Techniques for Plagiarism Removal from Research Papers",
      titleHi: "रिसर्च पेपर से प्लagiarism हटाने के लिए प्रभावी तकनीकें",
      excerptEn: "Learn proven methods to reduce plagiarism while maintaining the original meaning and academic integrity of your research.",
      excerptHi: "अपने शोध के मूल अर्थ और अकादमिक अखंडता को बनाए रखते हुए प्लagiarism कम करने के लिए सिद्ध तरीके सीखें।",
      contentEn: "Plagiarism is a serious academic offense. Learn paraphrasing techniques, proper citation methods, using Turnitin and iThenticate reports effectively, and how to rewrite content while preserving technical accuracy. Includes before/after examples and common mistakes to avoid.",
      contentHi: "प्लagiarism एक गंभीर अकादमिक अपराध है। पैराफ्रेजिंग तकनीकें, उचित उद्धरण विधियां, Turnitin रिपोर्ट का प्रभावी उपयोग सीखें।",
      category: "Academic Ethics",
      image: "/images/blog-plagiarism.jpg",
      tags: "Plagiarism,Turnitin,Academic Ethics,Writing",
      readTime: 6,
    },
    {
      slug: "conceptual-framework-development",
      titleEn: "How to Develop a Strong Conceptual Framework",
      titleHi: "मजबूत कांसेप्चुअल फ्रेमवर्क कैसे विकसित करें",
      excerptEn: "Step-by-step guide to building theoretical frameworks that strengthen your research foundation.",
      excerptHi: "अपने शोध की नींव को मजबूत करने वाले सैद्धांतिक ढांचे बनाने के लिए चरण-दर-चरण मार्गदर्शिका।",
      contentEn: "A conceptual framework visually represents the relationships between variables in your study. Learn how to identify dependent, independent, mediating, and moderating variables, select appropriate theories, use SEM tools like AMOS and SmartPLS, and create professional framework diagrams.",
      contentHi: "कल्पनात्मक ढांचा आपके अध्ययन में चर के बीच संबंधों का दृश्य प्रतिनिधित्व करता है। चर की पहचान करना, उपयुक्त सिद्धांत चुनना, SEM टूल्स का उपयोग करना सीखें।",
      category: "Methodology",
      image: "/images/blog-framework.jpg",
      tags: "Conceptual Framework,SEM,AMOS,SmartPLS",
      readTime: 8,
    },
    {
      slug: "avoid-predatory-journals",
      titleEn: "How to Identify and Avoid Predatory Journals",
      titleEn: "How to Identify and Avoid Predatory Journals",
      titleHi: "प्रिडेटरी जर्नल को कैसे पहचानें और बचें",
      excerptEn: "Protect your research reputation by learning to spot predatory publishers and find legitimate journals.",
      excerptHi: "प्रिडेटरी प्रकाशकों को पहचानना और वैध जर्नल खोजना सीखकर अपने शोध की प्रतिष्ठा की रक्षा करें।",
      contentEn: "Predatory journals exploit the open-access model. Learn warning signs like unrealistic turnaround times, fake impact factors, broad scopes, and lack of peer review. Use verified journal directories: DOAJ, Scopus Master List, Web of Science, and Beall's List criteria.",
      contentHi: "प्रिडेटरी जर्नल ओपन-एक्सेस मॉडल का दुरुपयोग करते हैं। चेतावनी संकेत जैसे अवास्तविक समय, नकली इम्पैक्ट फैक्टर सीखें।",
      category: "Publications",
      image: "/images/blog-predatory.jpg",
      tags: "Predatory Journals,Publication Ethics,DOAJ",
      readTime: 7,
    },
    {
      slug: "data-analysis-spss-r",
      titleEn: "Data Analysis Using SPSS, R, and Python for Researchers",
      titleHi: "शोधकर्ताओं के लिए SPSS, R और Python का उपयोग करके डेटा विश्लेषण",
      excerptEn: "Practical guide to statistical analysis tools commonly used in academic research across disciplines.",
      excerptHi: "विभिन्न विषयों में अकादमिक शोध में उपयोग किए जाने वाले सांख्यिकीय विश्लेषण उपकरणों के लिए व्यावहारिक मार्गदर्शिका।",
      contentEn: "Master the most popular statistical software packages. Covers descriptive statistics, regression analysis, ANOVA, SEM, machine learning basics, and data visualization. Includes code snippets, interpretation guidelines, and when to use each tool.",
      contentHi: "सबसे लोकप्रिय सांख्यिकीय सॉफ्टवेयर पैकेज में महारत हासिल करें। वर्णनात्मक सांख्यिकी, प्रतिगमन विश्लेषण, ANOVA, SEM कवर करता है।",
      category: "Methodology",
      image: "/images/blog-data-analysis.jpg",
      tags: "SPSS,R,Python,Data Analysis,Statistics",
      readTime: 10,
    },
    {
      slug: "research-paper-structure",
      titleEn: "Understanding Research Paper Structure: IMRAD Format",
      titleHi: "रिसर्च पेपर स्ट्रक्चर समझना: IMRAD फॉर्मेट",
      excerptEn: "Learn the standard IMRAD structure used by top journals and how to optimize each section.",
      excerptHi: "शीर्ष जर्नल द्वारा उपयोग किए जाने वाले मानक IMRAD संरचना को सीखें और प्रत्येक अनुभाग को कैसे अनुकूलित करें।",
      contentEn: "IMRAD (Introduction, Methods, Results, and Discussion) is the gold standard for scientific writing. Learn what each section should contain, common mistakes to avoid, word count guidelines, and how to write compelling abstracts and conclusions.",
      contentHi: "IMRAD (परिचय, विधियां, परिणाम और चर्चा) वैज्ञानिक लेखन का स्वर्ण मानक है। प्रत्येक अनुभाग में क्या होना चाहिए, सामान्य गलतियों से बचना सीखें।",
      category: "Writing Guide",
      image: "/images/blog-imrad.jpg",
      tags: "IMRAD,Paper Structure,Writing Guide",
      readTime: 7,
    },
    {
      slug: "citation-styles-guide",
      titleEn: "Complete Guide to Citation Styles: APA, MLA, Chicago, IEEE",
      titleHi: "साइटेशन स्टाइल की पूर्ण गाइड: APA, MLA, Chicago, IEEE",
      excerptEn: "Master the most commonly used citation formats in academic writing with practical examples.",
      excerptHi: "व्यावहारिक उदाहरणों के साथ अकादमिक लेखन में सबसे अधिक उपयोग किए जाने वाले उद्धरण प्रारूपों में महारत हासिल करें।",
      contentEn: "Proper citation is essential for academic integrity. This guide covers APA 7th edition, MLA 9th edition, Chicago Manual of Style, and IEEE citation formats. Includes in-text citations, reference list formatting, and special cases like online sources and multiple authors.",
      contentHi: "उचित उद्धरण अकादमिक अखंडता के लिए आवश्यक है। यह गाइड APA 7th, MLA 9th, Chicago, IEEE उद्धरण प्रारूपों को कवर करता है।",
      category: "Writing Guide",
      image: "/images/blog-citation.jpg",
      tags: "APA,MLA,Chicago,IEEE,Citation",
      readTime: 8,
    },
    {
      slug: "systematic-review-vs-meta-analysis",
      titleEn: "Systematic Review vs Meta-Analysis: Key Differences",
      titleHi: "सिस्टमैटिक रिव्यू बनाम मेटा-एनालिसिस: मुख्य अंतर",
      excerptEn: "Understand when to choose a systematic review versus a meta-analysis for your research synthesis.",
      excerptHi: "अपने शोध संश्लेषण के लिए सिस्टमैटिक रिव्यू बनाम मेटा-एनालिसिस को कब चुनना है यह समझें।",
      contentEn: "While both synthesize existing research, systematic reviews qualitatively summarize findings, while meta-analyses statistically pool data. Learn PRISMA guidelines, forest plots, heterogeneity assessment, and when each approach is most appropriate.",
      contentHi: "दोनों मौजूदा शोध का संश्लेषण करते हैं, लेकिन सिस्टमैटिक रिव्यू गुणात्मक रूप से निष्कर्षों का सारांश देते हैं, जबकि मेटा-एनालिसेस सांख्यिकीय रूप से डेटा पूल करता है।",
      category: "Methodology",
      image: "/images/blog-meta.jpg",
      tags: "Systematic Review,Meta-Analysis,PRISMA",
      readTime: 9,
    },
    {
      slug: "chatgpt-for-research",
      titleEn: "How to Use ChatGPT Effectively for Academic Research",
      titleHi: "अकादमिक शोध के लिए ChatGPT का प्रभावी ढंग से उपयोग कैसे करें",
      excerptEn: "Ethical ways to leverage ChatGPT and LLMs in your research workflow without compromising integrity.",
      excerptHi: "अखंडता से समझौता किए बिना अपनी शोध वर्कफ्लो में ChatGPT और LLM का लाभ उठाने के नैतिक तरीके।",
      contentEn: "ChatGPT can help with brainstorming, literature summaries, coding assistance, and language polishing. Learn prompt engineering techniques, limitations to be aware of, institutional policies, and how to disclose AI usage in your publications.",
      contentHi: "ChatGPT ब्रेनस्टॉर्मिंग, साहित्य सारांश, कोडिंग सहायता और भाषा पॉलिशिंग में मदद कर सकता है। प्रॉम्प्ट इंजीनियरिंग तकनीकें सीखें।",
      category: "AI Tools",
      image: "/images/blog-chatgpt.jpg",
      tags: "ChatGPT,AI,LLM,Research Ethics",
      readTime: 7,
    },
    {
      slug: "ugc-care-journals",
      titleEn: "UGC CARE Journals: Complete List and Publication Guide",
      titleHi: "UGC CARE जर्नल: पूर्ण सूची और प्रकाशन गाइड",
      excerptEn: "Navigate the UGC CARE list for Indian researchers seeking publication opportunities.",
      excerptHi: "प्रकाशन अवसरों की तलाश करने वाले भारतीय शोधकर्ताओं के लिए UGC CARE सूची को नेविगेट करें।",
      contentEn: "UGC CARE (Consortium for Academic and Research Ethics) maintains lists of approved journals for Indian academics. Learn about Group I and Group II journals, the CARE scoring system, how to check journal authenticity, and strategies for successful publication.",
      contentHi: "UGC CARE भारतीय अकादमिक्स के लिए अनुमोदित जर्नल की सूची बनाए रखता है। ग्रुप I और ग्रुप II जर्नल, CARE स्कोरिंग सिस्टम सीखें।",
      category: "Publications",
      image: "/images/blog-ugc.jpg",
      tags: "UGC CARE,Indian Researchers,Publication",
      readTime: 8,
    },
    {
      slug: "thesis-writing-tips",
      titleEn: "10 Essential Tips for Writing a Winning PhD Thesis",
      titleHi: "एक सफल पीएचडी थीसिस लेखन के लिए 10 आवश्यक टिप्स",
      excerptEn: "Expert advice from successful PhD graduates on structuring and writing your doctoral thesis.",
      excerptHi: "अपना डॉक्टरेट थीसिस संरचित करने और लिखने पर सफल पीएचडी स्नातकों से विशेषज्ञ सलाह।",
      contentEn: "Writing a PhD thesis is a marathon, not a sprint. Learn about chapter structuring, maintaining consistency, dealing with supervisor feedback, writing the methodology chapter, handling data chapters, and preparing for the viva voce examination.",
      contentHi: "पीएचडी थीसिस लेखन एक मैराथन है। अध्याय संरचना, निरंतरता बनाए रखना, सुपरवाइजर फीडबैक से निपटना सीखें।",
      category: "Writing Guide",
      image: "/images/blog-thesis.jpg",
      tags: "PhD,Thesis Writing,Dissertation,Doctoral",
      readTime: 9,
    },
    {
      slug: "grant-proposal-writing",
      titleEn: "How to Write a Winning Research Grant Proposal",
      titleHi: "एक सफल रिसर्च ग्रांट प्रस्ताव कैसे लिखें",
      excerptEn: "Secure funding for your research with compelling grant proposals that stand out.",
      excerptHi: "खड़े होने वाले सम्मोहक अनुदान प्रस्तावों के साथ अपने शोध के लिए वित्तपोषण सुरक्षित करें।",
      contentEn: "Grant writing requires a unique skill set. Learn how to structure your proposal, write compelling aims and objectives, develop a realistic budget and timeline, address reviewer criteria, and avoid common pitfalls that lead to rejection.",
      contentHi: "अनुदान लेखन एक अद्वितीय कौशल सेट की आवश्यकता है। अपना प्रस्ताव कैसे संरचित करें, सम्मोहक उद्देश्य कैसे लिखें सीखें।",
      category: "Writing Guide",
      image: "/images/blog-grant.jpg",
      tags: "Grant Proposal,Funding,Research",
      readTime: 8,
    },
    {
      slug: "qualitative-vs-quantitative",
      titleEn: "Qualitative vs Quantitative Research: Choosing Your Approach",
      titleHi: "गुणात्मक बनाम मात्रात्मक शोध: अपना दृष्टिकोण चुनना",
      excerptEn: "Understand the fundamental differences and choose the right research paradigm for your study.",
      excerptHi: "मौलिक अंतर को समझें और अपने अध्ययन के लिए सही शोध प्रतिमान चुनें।",
      contentEn: "The choice between qualitative and quantitative methods defines your entire research design. Explore positivism vs interpretivism, data collection techniques, analysis methods, validity and reliability concerns, and when mixed methods offer the best solution.",
      contentHi: "गुणात्मक और मात्रात्मक विधियों के बीच का चयन आपके पूरे शोध डिजाइन को परिभाषित करता है। पॉजिटिविज्म बनाम इंटरप्रिटिविज्म का अन्वेषण करें।",
      category: "Methodology",
      image: "/images/blog-qual-quant.jpg",
      tags: "Qualitative,Quantitative,Mixed Methods",
      readTime: 7,
    },
    {
      slug: "mendeley-zotero-reference",
      titleEn: "Reference Management with Mendeley and Zotero",
      titleHi: "Mendeley और Zotero के साथ रेफरेंस मैनेजमेंट",
      excerptEn: "Organize your references efficiently with these powerful free reference management tools.",
      excerptHi: "इन शक्तिशाली मुफ्त रेफरेंस मैनेजमेंट टूल्स के साथ अपने संदर्भों को कुशलतापूर्वक व्यवस्थित करें।",
      contentEn: "Reference management is crucial for large research projects. Learn how to install and configure Mendeley and Zotero, import references from databases, organize libraries, generate citations in Word/Google Docs, and collaborate with co-authors.",
      contentHi: "बड़े शोध परियोजनाओं के लिए संदर्भ प्रबंधन महत्वपूर्ण है। Mendeley और Zotero को कॉन्फ़िगर करना, संदर्भ आयात करना सीखें।",
      category: "AI Tools",
      image: "/images/blog-mendeley.jpg",
      tags: "Mendeley,Zotero,Reference Management",
      readTime: 6,
    },
    {
      slug: "peer-review-process",
      titleEn: "Understanding the Peer Review Process in Academic Publishing",
      titleHi: "अकादमिक प्रकाशन में पीयर रिव्यू प्रक्रिया को समझना",
      excerptEn: "Navigate peer review with confidence: types of review, what reviewers look for, and how to respond.",
      excerptHi: "आत्मविश्वास के साथ पीयर रिव्यू को नेविगेट करें: रिव्यू के प्रकार, समीक्षक क्या देखते हैं, और कैसे जवाब दें।",
      contentEn: "Peer review is the quality control mechanism of science. Learn about single-blind, double-blind, and open review systems. Understand common reviewer comments, how to write effective response letters, and strategies for handling rejection and revision requests.",
      contentHi: "पीयर रिव्यू विज्ञान की गुणवत्ता नियंत्रण तंत्र है। सिंगल-ब्लाइंड, डबल-ब्लाइंड, ओपन रिव्यू सिस्टम के बारे में जानें।",
      category: "Publications",
      image: "/images/blog-peer-review.jpg",
      tags: "Peer Review,Publishing,Reviewer Comments",
      readTime: 8,
    },
    {
      slug: "ai-detection-tools",
      titleEn: "AI Detection Tools and How to Humanize AI Content",
      titleHi: "AI डिटेक्शन टूल्स और AI कंटेंट को ह्यूमनाइज़ कैसे करें",
      excerptEn: "Stay ahead of AI detectors while using AI tools ethically in your research workflow.",
      excerptHi: "अपनी शोध वर्कफ्लो में AI टूल्स का नैतिक रूप से उपयोग करते हुए AI डिटेक्टर्स से आगे रहें।",
      contentEn: "With journals adopting AI detection, researchers need to understand tools like GPTZero, Turnitin's AI detector, and Originality.ai. Learn how AI detection works, false positive risks, effective humanization techniques, and institutional policies on AI use.",
      contentHi: "जर्नल AI डिटेक्शन अपनाने के साथ, शोधकर्ताओं को GPTZero, Turnitin AI डिटेक्टर को समझने की आवश्यकता है।",
      category: "AI Tools",
      image: "/images/blog-ai-detect.jpg",
      tags: "AI Detection,GPTZero,Humanize AI",
      readTime: 7,
    },
    {
      slug: "open-access-vs-subscription",
      titleEn: "Open Access vs Subscription Journals: What Researchers Should Know",
      titleHi: "ओपन एक्सेस बनाम सब्सक्रिप्शन जर्नल: शोधकर्ताओं को क्या जानना चाहिए",
      excerptEn: "Make informed decisions about where to publish based on access models, costs, and impact.",
      excerptHi: "एक्सेस मॉडल, लागत और प्रभाव के आधार पर प्रकाशित करने के लिए सूचित निर्णय लें।",
      contentEn: "The publishing landscape is divided between open access (gold, green, hybrid) and traditional subscription models. Learn about APCs (Article Processing Charges), embargo periods, funder mandates, and how to choose the right model for your research career.",
      contentHi: "प्रकाशन परिदृश्य ओपन एक्सेस (गोल्ड, ग्रीन, हाइब्रिड) और पारंपरिक सब्सक्रिप्शन मॉडल के बीच विभाजित है।",
      category: "Publications",
      image: "/images/blog-open-access.jpg",
      tags: "Open Access,Subscription,APC,Publishing",
      readTime: 7,
    },
    {
      slug: "research-ethics-guide",
      titleEn: "Research Ethics: A Practical Guide for Scholars",
      titleHi: "शोध नैतिकता: विद्वानों के लिए एक व्यावहारिक मार्गदर्शिका",
      excerptEn: "Ensure your research meets ethical standards with this comprehensive guide to research integrity.",
      excerptHi: "शोध अखंडता के लिए इस व्यापक मार्गदर्शिका के साथ सुनिश्चित करें कि आपका शोध नैतिक मानकों को पूरा करता है।",
      contentEn: "Research ethics covers informed consent, plagiarism, data fabrication, conflicts of interest, and animal/human subject protection. Learn about IRB approvals, ethical guidelines from COPE and ICMJE, and how to maintain integrity throughout your research.",
      contentHi: "शोध नैतिकता सूचित सहमति, प्लagiarism, डेटा फैब्रिकेशन, हितों का टकराव को कवर करती है।",
      category: "Academic Ethics",
      image: "/images/blog-ethics.jpg",
      tags: "Research Ethics,IRB,COPE,Integrity",
      readTime: 8,
    },
    {
      slug: "google-scholar-tips",
      titleEn: "Advanced Google Scholar Tips for Researchers",
      titleHi: "शोधकर्ताओं के लिए एडवांस्ड Google Scholar टिप्स",
      excerptEn: "Maximize your literature search efficiency with these powerful Google Scholar features.",
      excerptHi: "इन शक्तिशाली Google Scholar सुविधाओं के साथ अपनी साहित्य खोज दक्षता को अधिकतम करें।",
      contentEn: "Go beyond basic keyword searches. Learn about author alerts, citation tracking, related articles, Boolean operators, advanced search filters, My Library features, and how to set up Google Scholar profiles for better research visibility.",
      contentHi: "बुनियादी कीवर्ड खोज से परे जाएं। लेखक अलर्ट, उद्धरण ट्रैकिंग, संबंधित लेख, बूलियन ऑपरेटर सीखें।",
      category: "AI Tools",
      image: "/images/blog-scholar.jpg",
      tags: "Google Scholar,Research Tools,Literature Search",
      readTime: 6,
    },
    {
      slug: "network-analysis-bibliometrics",
      titleEn: "Bibliometric Analysis and Network Visualization Tools",
      titleHi: "बिब्लियोमेट्रिक विश्लेषण और नेटवर्क विज़ुअलाइज़ेशन टूल्स",
      excerptEn: "Map the research landscape with VOSviewer, CiteSpace, and Gephi for impactful bibliometric studies.",
      excerptHi: "प्रभावशाली बिब्लियोमेट्रिक अध्ययनों के लिए VOSviewer, CiteSpace और Gephi के साथ शोध परिदृश्य का मानचित्रण करें।",
      contentEn: "Bibliometrics uses quantitative methods to analyze academic literature. Learn about co-citation analysis, keyword co-occurrence, author collaboration networks, and how to create stunning visualizations using VOSviewer, CiteSpace, and Biblioshiny.",
      contentHi: "बिब्लियोमेट्रिक्स अकादमिक साहित्य का विश्लेषण करने के लिए मात्रात्मक विधियों का उपयोग करता है। को-साइटेशन विश्लेषण सीखें।",
      category: "AI Tools",
      image: "/images/blog-vosviewer.jpg",
      tags: "Bibliometrics,VOSviewer,CiteSpace,Gephi",
      readTime: 8,
    },
    {
      slug: "cross-sectional-longitudinal",
      titleEn: "Cross-Sectional vs Longitudinal Studies: Design Considerations",
      titleHi: "क्रॉस-सेक्शनल बनाम लॉन्गीट्यूडिनल स्टडीज: डिज़ाइन विचार",
      excerptEn: "Choose the right study design for your research questions with this comprehensive comparison.",
      excerptHi: "इस व्यापक तुलना के साथ अपने शोध प्रश्नों के लिए सही अध्ययन डिज़ाइन चुनें।",
      contentEn: "Study design fundamentally affects your findings. Compare cross-sectional (snapshot) and longitudinal (over time) approaches. Learn about cohort studies, panel data, repeated measures, attrition handling, and when each design is most powerful.",
      contentHi: "अध्ययन डिज़ाइन मौलिक रूप से आपके निष्कर्षों को प्रभावित करता है। क्रॉस-सेक्शनल (स्नैपशॉट) और लॉन्गीट्यूडिनल (समय के साथ) दृष्टिकोणों की तुलना करें।",
      category: "Methodology",
      image: "/images/blog-study-design.jpg",
      tags: "Cross-Sectional,Longitudinal,Study Design",
      readTime: 7,
    },
  ]);
  console.log("Blog posts seeded.");

  // ── Seed Testimonials ──────────────────────────────
  await db.insert(testimonials).values([
    { name: "Dr. Rajesh Kumar Sharma", designation: "Associate Professor", university: "IIT Delhi", contentEn: "AcademicHelp transformed my research paper on renewable energy. Their expertise in SCI journal publication is unmatched. My paper got accepted in Energy Policy within 3 months!", contentHi: "AcademicHelp ने नवीकरणीय ऊर्जा पर मेरे शोध पत्र को बदल दिया। SCI जर्नल प्रकाशन में उनकी विशेषज्ञता अद्वितीय है।", rating: 5, featured: 1, sortOrder: 1 },
    { name: "Dr. Priya Venkatesh", designation: "Assistant Professor", university: "IIT Madras", contentEn: "The thesis writing support was phenomenal. From methodology design to final submission, every step was handled with academic precision. Highly recommended for PhD scholars!", contentHi: "थीसिस लेखन सहायता असाधारण थी। मेथडोलॉजी डिज़ाइन से लेकर अंतिम सबमिशन तक, हर कदम अकादमिक सटीकता के साथ संभाला गया।", rating: 5, featured: 1, sortOrder: 2 },
    { name: "Prof. Sunil Patil", designation: "Professor", university: "University of Mumbai", contentEn: "Their peer review service identified critical gaps in my manuscript that I had overlooked. The detailed feedback significantly improved the quality of my publication.", contentHi: "उनकी पीयर रिव्यू सेवा ने मेरी पांडुलिपि में महत्वपूर्ण कमियों की पहचान की जिन्हें मैंने अनदेखा कर दिया था।", rating: 5, featured: 1, sortOrder: 3 },
    { name: "Dr. Ananya Gupta", designation: "Research Scholar", university: "JNU Delhi", contentEn: "I was struggling with my conceptual framework until I found AcademicHelp. Their methodology experts designed a robust SEM model that strengthened my entire research.", contentHi: "मैं अपने कांसेप्चुअल फ्रेमवर्क के साथ संघर्ष कर रही थी जब तक मैंने AcademicHelp नहीं खोजा। उनके विशेषज्ञों ने एक मजबूत SEM मॉडल डिज़ाइन किया।", rating: 5, featured: 1, sortOrder: 4 },
    { name: "Dr. Mohan Reddy", designation: "Associate Professor", university: "IIT Hyderabad", contentEn: "The plagiarism removal service was excellent. They reduced my Turnitin similarity from 35% to 8% while preserving all technical content. Truly professional work!", contentHi: "प्लagiarism रिमूवल सेवा उत्कृष्ट थी। उन्होंने मेरी Turnitin समानता को 35% से 8% तक कम कर दिया।", rating: 5, featured: 1, sortOrder: 5 },
    { name: "Dr. Sunita Devi", designation: "Professor", university: "Banaras Hindu University", contentEn: "AcademicHelp helped me publish 4 papers in Scopus-indexed journals in just one year. Their understanding of journal requirements is truly remarkable.", contentHi: "AcademicHelp ने मुझे सिर्फ एक साल में 4 पेपर Scopus-indexed जर्नल में प्रकाशित करने में मदद की।", rating: 5, featured: 0, sortOrder: 6 },
    { name: "Dr. Karthik Subramanian", designation: "Assistant Professor", university: "Anna University", contentEn: "The review paper they helped me write on machine learning applications got published in IEEE Access. Their systematic approach to literature synthesis is impressive.", contentHi: "उन्होंने मेरी मशीन लर्निंग अनुप्रयोगों पर समीक्षा पत्र लेखन में मदद की जो IEEE Access में प्रकाशित हुआ।", rating: 5, featured: 0, sortOrder: 7 },
    { name: "Dr. Fatima Khan", designation: "Research Fellow", university: "Aligarh Muslim University", contentEn: "Outstanding support for my qualitative research methodology. Their experts guided me through thematic analysis and helped me structure my findings beautifully.", contentHi: "मेरे गुणात्मक शोध मेथडोलॉजी के लिए उत्कृष्ट सहायता। उनके विशेषज्ञों ने मुझे थीमैटिक विश्लेषण के माध्यम से मार्गदर्शन दिया।", rating: 5, featured: 0, sortOrder: 8 },
    { name: "Prof. Ramesh Joshi", designation: "Head of Department", university: "University of Pune", contentEn: "As a department head, I recommend AcademicHelp to all my research students. Their end-to-end publication support has resulted in numerous successful journal acceptances.", contentHi: "विभागाध्यक्ष के रूप में, मैं अपने सभी शोध छात्रों को AcademicHelp की सलाह देता हूं। उनकी अंत-से-अंत प्रकाशन सहायता से कई सफल जर्नल स्वीकृति मिली हैं।", rating: 5, featured: 0, sortOrder: 9 },
    { name: "Dr. Meera Nair", designation: "Assistant Professor", university: "IISc Bangalore", contentEn: "The AI content humanization service was a lifesaver. They helped me modify my AI-assisted draft to pass all detection tools while maintaining academic quality.", contentHi: "AI कंटेंट ह्यूमनाइजेशन सेवा एक लाइफसेवर थी। उन्होंने मेरी AI-सहायता प्राप्त ड्राफ्ट को संशोधित करने में मदद की।", rating: 5, featured: 0, sortOrder: 10 },
    { name: "Dr. Amitabh Singh", designation: "Professor", university: "IIT Kanpur", contentEn: "Exceptional quality in research paper writing. Their team's domain expertise in engineering research ensured my paper met the highest standards of Q1 journals.", contentHi: "रिसर्च पेपर लेखन में असाधारण गुणवत्ता। इंजीनियरिंग शोध में उनकी टीम के डोमेन विशेषज्ञता ने सुनिश्चित किया कि मेरा पेपर Q1 जर्नल के उच्चतम मानकों को पूरा करे।", rating: 5, featured: 0, sortOrder: 11 },
    { name: "Dr. Lakshmi Prasad", designation: "Associate Professor", university: "University of Madras", contentEn: "Their SPSS and statistical analysis support was crucial for my research. The data interpretation was accurate and professionally presented.", contentHi: "उनकी SPSS और सांख्यिकीय विश्लेषण सहायता मेरे शोध के लिए महत्वपूर्ण थी। डेटा व्याख्या सटीक और पेशेवर रूप से प्रस्तुत की गई थी।", rating: 5, featured: 0, sortOrder: 12 },
    { name: "Dr. Harish Chandra", designation: "Research Scholar", university: "IIT Roorkee", contentEn: "From conceptual framework to final publication, AcademicHelp was with me at every step. My paper on structural engineering is now published in a top SCI journal.", contentHi: "कांसेप्चुअल फ्रेमवर्क से लेकर अंतिम प्रकाशन तक, AcademicHelp हर कदम पर मेरे साथ था।", rating: 5, featured: 0, sortOrder: 13 },
    { name: "Dr. Kavita Sharma", designation: "Assistant Professor", university: "Delhi University", contentEn: "The speed and quality of their literature review service amazed me. They synthesized 200+ papers into a coherent narrative that formed the backbone of my research.", contentHi: "उनकी साहित्य समीक्षा सेवा की गति और गुणवत्ता ने मुझे चकित कर दिया। उन्होंने 200+ पेपर को एक सुसंगत कथा में संश्लेषित किया।", rating: 5, featured: 0, sortOrder: 14 },
    { name: "Dr. Venkata Rao", designation: "Professor", university: "Andhra University", contentEn: "I have used AcademicHelp's services for multiple projects. Their consistency in quality and commitment to deadlines makes them the best in the field.", contentHi: "मैंने कई परियोजनाओं के लिए AcademicHelp की सेवाओं का उपयोग किया है। गुणवत्ता में स्थिरता और समय सीमा के प्रति प्रतिबद्धता उन्हें क्षेत्र में सबसे अच्छा बनाती है।", rating: 5, featured: 0, sortOrder: 15 },
    { name: "Dr. Neha Gupta", designation: "Research Fellow", university: "IIT Kharagpur", contentEn: "Their guidance on choosing the right journal was invaluable. They helped me target the perfect journal for my research domain, resulting in quick acceptance.", contentHi: "सही जर्नल चुनने पर उनका मार्गदर्शन अमूल्य था। उन्होंने मेरे शोध डोमेन के लिए सही जर्नल को लक्षित करने में मदद की।", rating: 5, featured: 0, sortOrder: 16 },
    { name: "Prof. Arun Kumar Mehta", designation: "Dean of Research", university: "BITS Pilani", contentEn: "AcademicHelp's publication support has helped numerous faculty members in our institute achieve their research goals. A truly professional academic partner.", contentHi: "AcademicHelp की प्रकाशन सहायता ने हमारे संस्थान में कई संकाय सदस्यों को उनके शोध लक्ष्यों को प्राप्त करने में मदद की है।", rating: 5, featured: 0, sortOrder: 17 },
    { name: "Dr. Shalini Pandey", designation: "Assistant Professor", university: "University of Allahabad", contentEn: "The review paper on sustainable development they helped me write received outstanding comments from reviewers. Their writing quality is truly world-class.", contentHi: "सतत विकास पर उनकी मदद से लिखा गया समीक्षा पत्र समीक्षकों से उत्कृष्ट टिप्पणियां प्राप्त हुई।", rating: 5, featured: 0, sortOrder: 18 },
    { name: "Dr. Manoj Tiwari", designation: "Associate Professor", university: "NIT Trichy", contentEn: "Their expertise in mixed-methods research design helped me structure a complex study combining quantitative surveys and qualitative interviews.", contentHi: "मिश्रित-विधि शोध डिज़ाइन में उनकी विशेषज्ञता ने मुझे मात्रात्मक सर्वेक्षण और गुणात्मक साक्षात्कार को जोड़ते हुए एक जटिल अध्ययन संरचित करने में मदद की।", rating: 5, featured: 0, sortOrder: 19 },
    { name: "Dr. Anjali Menon", designation: "Professor", university: "Cochin University", contentEn: "I was impressed by their understanding of bibliometric analysis. They used VOSviewer to create stunning visualizations that greatly enhanced my review paper.", contentHi: "बिब्लियोमेट्रिक विश्लेषण में उनकी समझ से मैं प्रभावित थी। उन्होंने VOSviewer का उपयोग करके शानदार विज़ुअलाइज़ेशन बनाए।", rating: 5, featured: 0, sortOrder: 20 },
    { name: "Dr. Ravi Shankar Iyer", designation: "Research Scholar", university: "IISER Pune", contentEn: "The grant proposal writing service secured me a major DST funding. Their ability to articulate research significance is remarkable.", contentHi: "ग्रांट प्रस्ताव लेखन सेवा ने मुझे एक प्रमुख DST फंडिंग सुरक्षित करने में मदद की। शोध महत्व को स्पष्ट करने की उनकी क्षमता उल्लेखनीय है।", rating: 5, featured: 0, sortOrder: 21 },
    { name: "Dr. Pooja Agarwal", designation: "Assistant Professor", university: "University of Rajasthan", contentEn: "AcademicHelp's plagiarism removal service is exceptional. They maintained the technical accuracy while achieving less than 10% similarity on Turnitin.", contentHi: "AcademicHelp की प्लagiarism रिमूवल सेवा असाधारण है। उन्होंने Turnitin पर 10% से कम समानता प्राप्त करते हुए तकनीकी सटीकता बनाए रखी।", rating: 5, featured: 0, sortOrder: 22 },
    { name: "Prof. Deepak Chopra", designation: "Head of Department", university: "Thapar University", contentEn: "We have a institutional collaboration with AcademicHelp. Their support has significantly improved our department's research output and publication metrics.", contentHi: "हमारे पास AcademicHelp के साथ संस्थागत सहयोग है। उनकी सहायता से हमारे विभाग के शोध परिणाम और प्रकाशन मेट्रिक्स में significant सुधार हुआ है।", rating: 5, featured: 0, sortOrder: 23 },
    { name: "Dr. Shweta Banerjee", designation: "Associate Professor", university: "Jadavpur University", contentEn: "Their support in writing a systematic review on nanotechnology was comprehensive. They followed PRISMA guidelines meticulously and delivered outstanding quality.", contentHi: "नैनोटेक्नोलॉजी पर एक सिस्टमैटिक रिव्यू लिखने में उनकी सहायता व्यापक थी। उन्होंने PRISMA दिशानिर्देशों का सावधानीपूर्वक पालन किया।", rating: 5, featured: 0, sortOrder: 24 },
    { name: "Dr. Gopalakrishnan Nair", designation: "Professor", university: "University of Kerala", contentEn: "The confidentiality and professionalism of AcademicHelp is commendable. As a senior researcher, I trust them with my most sensitive research projects.", contentHi: "AcademicHelp की गोपनीयता और पेशेवरता प्रशंसनीय है। एक वरिष्ठ शोधकर्ता के रूप में, मैं उन्हें अपनी सबसे संवेदनशील शोध परियोजनाओं पर भरोसा करता हूं।", rating: 5, featured: 0, sortOrder: 25 },
    { name: "Dr. Seema Malhotra", designation: "Research Fellow", university: "IIT Guwahati", contentEn: "Their guidance on AMOS and structural equation modeling was clear and practical. I successfully defended my thesis with their methodological support.", contentHi: "AMOS और स्ट्रक्चरल इक्वेशन मॉडलिंग पर उनका मार्गदर्शन स्पष्ट और व्यावहारिक था। मैंने उनकी मेथडोलॉजिकल सहायता के साथ सफलतापूर्वक अपनी थीसिस का बचाव किया।", rating: 5, featured: 0, sortOrder: 26 },
    { name: "Dr. Prakash Joshi", designation: "Assistant Professor", university: "NIT Warangal", contentEn: "AcademicHelp assisted me in publishing a paper in Technovation journal. Their understanding of innovation management research is truly impressive.", contentHi: "AcademicHelp ने मुझे Technovation जर्नल में एक पेपर प्रकाशित करने में सहायता की। नवाचार प्रबंधन शोध में उनकी समझ वास्तव में प्रभावशाली है।", rating: 5, featured: 0, sortOrder: 27 },
    { name: "Dr. Radhika Iyer", designation: "Professor", university: "University of Hyderabad", contentEn: "The team at AcademicHelp provided exceptional support for my longitudinal study design. Their expertise in panel data analysis was crucial for my research.", contentHi: "AcademicHelp की टीम ने मेरे लॉन्गीट्यूडिनल अध्ययन डिज़ाइन के लिए असाधारण सहायता प्रदान की। पैनल डेटा विश्लेषण में उनकी विशेषज्ञता महत्वपूर्ण थी।", rating: 5, featured: 0, sortOrder: 28 },
    { name: "Dr. Sanjay Gupta", designation: "Associate Professor", university: "IIT BHU", contentEn: "I highly recommend AcademicHelp for their systematic review writing service. Their literature search was exhaustive and synthesis was methodologically sound.", contentHi: "मैं उनकी सिस्टमैटिक रिव्यू लेखन सेवा के लिए AcademicHelp की अत्यधिक सलाह देता हूं। उनकी साहित्य खोज व्यापक थी और संश्लेषण मेथडोलॉजिकली साउंड था।", rating: 5, featured: 0, sortOrder: 29 },
    { name: "Dr. Priyanka Reddy", designation: "Research Scholar", university: "University of Mysore", contentEn: "Their help with data analysis using R programming was outstanding. They guided me through complex statistical procedures with patience and expertise.", contentHi: "R प्रोग्रामिंग का उपयोग करके डेटा विश्लेषण में उनकी मदद उत्कृष्ट थी। उन्होंने धैर्य और विशेषज्ञता के साथ जटिल सांख्यिकीय प्रक्रियाओं के माध्यम से मार्गदर्शन दिया।", rating: 5, featured: 0, sortOrder: 30 },
    { name: "Prof. Vikram Sethi", designation: "Dean of Academics", university: "VIT Vellore", contentEn: "AcademicHelp has been our preferred research partner for three years. Their consistent quality and adherence to academic ethics makes them stand out.", contentHi: "AcademicHelp तीन वर्षों से हमारे पसंदीदा शोध साझेदार रहा है। उनकी लगातार गुणवत्ता और अकादमिक नैतिकता का पालन उन्हें खड़ा करता है।", rating: 5, featured: 0, sortOrder: 31 },
    { name: "Dr. Meenakshi Sundaram", designation: "Assistant Professor", university: "Anna University", contentEn: "The conceptual framework they developed for my supply chain research was brilliant. It significantly strengthened the theoretical foundation of my study.", contentHi: "मेरे सप्लाई चेन शोध के लिए उनके द्वारा विकसित कांसेप्चुअल फ्रेमवर्क शानदार था। इसने मेरे अध्ययन के सैद्धांतिक आधार को significant रूप से मजबूत किया।", rating: 5, featured: 0, sortOrder: 32 },
    { name: "Dr. Arjun Khanna", designation: "Professor", university: "Panjab University", contentEn: "Outstanding support for my meta-analysis on healthcare interventions. Their statistical expertise and attention to detail ensured a flawless manuscript.", contentHi: "हैल्थकेयर हस्तक्षेप पर मेरी मेटा-एनालिसिस के लिए उत्कृष्ट सहायता। उनकी सांख्यिकीय विशेषज्ञता और विवरण पर ध्यान ने एक निर्दोष पांडुलिपि सुनिश्चित की।", rating: 5, featured: 0, sortOrder: 33 },
    { name: "Dr. Tanvi Desai", designation: "Research Fellow", university: "IIT Gandhinagar", contentEn: "AcademicHelp's AI detection removal service helped me ethically use AI tools in my research workflow. They maintained academic integrity throughout.", contentHi: "AcademicHelp की AI डिटेक्शन रिमूवल सेवा ने मुझे अपनी शोध वर्कफ्लो में AI टूल्स का नैतिक रूप से उपयोग करने में मदद की। उन्होंने पूरी तरह से अकादमिक अखंडता बनाए रखी।", rating: 5, featured: 0, sortOrder: 34 },
    { name: "Dr. Naveen Chandra", designation: "Associate Professor", university: "NIT Calicut", contentEn: "Their expertise in getting papers published in ABDC A* journals is remarkable. They understand the exact requirements of top-tier business journals.", contentHi: "ABDC A* जर्नल में पेपर प्रकाशित करने में उनकी विशेषज्ञता उल्लेखनीय है। वे शीर्ष-स्तरीय बिजनेस जर्नल की सटीक आवश्यकताओं को समझते हैं।", rating: 5, featured: 0, sortOrder: 35 },
    { name: "Dr. Aarti Sharma", designation: "Assistant Professor", university: "University of Lucknow", contentEn: "The grant proposal they helped me write secured SERB funding for my project. Their understanding of funding agency expectations is exceptional.", contentHi: "उन्होंने जो ग्रांट प्रस्ताव लिखने में मेरी मदद की उसने मेरे प्रोजेक्ट के लिए SERB फंडिंग सुरक्षित की।", rating: 5, featured: 0, sortOrder: 36 },
    { name: "Prof. Krishnamurthy Iyer", designation: "Head of Research", university: "SRM University", contentEn: "We have seen a 300% increase in our publication output since collaborating with AcademicHelp. Their systematic approach to research support is transformative.", contentHi: "AcademicHelp के साथ सहयोग करने के बाद से हमारे प्रकाशन परिणाम में 300% की वृद्धि देखी गई है।", rating: 5, featured: 0, sortOrder: 37 },
    { name: "Dr. Jyoti Patel", designation: "Professor", university: "Gujarat University", contentEn: "Their bibliometric analysis service using VOSviewer provided invaluable insights into my research domain. The visualizations were publication-ready.", contentHi: "VOSviewer का उपयोग करके उनकी बिब्लियोमेट्रिक विश्लेषण सेवा ने मेरे शोध डोमेन में अमूल्य अंतर्दृष्टि प्रदान की।", rating: 5, featured: 0, sortOrder: 38 },
    { name: "Dr. Rohit Malhotra", designation: "Research Scholar", university: "IIT Patna", contentEn: "AcademicHelp guided me through the complex process of publishing in Nature-indexed journals. Their expertise made the impossible seem achievable.", contentHi: "AcademicHelp ने मुझे Nature-indexed जर्नल में प्रकाशन की जटिल प्रक्रिया के माध्यम से मार्गदर्शन दिया। उनकी विशेषज्ञता ने असंभव को प्राप्त करने योग्य बना दिया।", rating: 5, featured: 0, sortOrder: 39 },
    { name: "Dr. Sangeeta Rani", designation: "Associate Professor", university: "Punjab Agricultural University", contentEn: "Their support in agricultural research publication was outstanding. They understood the unique challenges of publishing in agriculture journals.", contentHi: "कृषि शोध प्रकाशन में उनकी सहायता उत्कृष्ट थी। उन्होंने कृषि जर्नल में प्रकाशन की अद्वितीय चुनौतियों को समझा।", rating: 5, featured: 0, sortOrder: 40 },
    { name: "Dr. Mahesh Kulkarni", designation: "Assistant Professor", university: "Shivaji University", contentEn: "The thesis formatting and editing service was meticulous. They ensured every citation, table, and figure met university guidelines perfectly.", contentHi: "थीसिस फॉर्मेटिंग और एडिटिंग सेवा सावधानीपूर्वक थी। उन्होंने सुनिश्चित किया कि हर उद्धरण, तालिका और आंकड़ा पूरी तरह से विश्वविद्यालय दिशानिर्देशों को पूरा करे।", rating: 5, featured: 0, sortOrder: 41 },
    { name: "Dr. Anuradha Menon", designation: "Professor", university: "Calicut University", contentEn: "Their systematic approach to research paper writing helped me publish in Q1 management journals. The quality of their work is consistently excellent.", contentHi: "रिसर्च पेपर लेखन के लिए उनका व्यवस्थित दृष्टिकोण मुझे Q1 मैनेजमेंट जर्नल में प्रकाशित करने में मदद करता है। उनके काम की गुणवत्ता लगातार उत्कृष्ट है।", rating: 5, featured: 0, sortOrder: 42 },
    { name: "Dr. Chandrashekhar Rao", designation: "Research Fellow", university: "University of Agricultural Sciences", contentEn: "Exceptional support for my meta-analysis. Their forest plot creation and heterogeneity analysis were methodologically impeccable.", contentHi: "मेरी मेटा-एनालिसिस के लिए असाधारण सहायता। उनका फॉरेस्ट प्लॉट निर्माण और विषमता विश्लेषण मेथडोलॉजिकली बेजोड़ था।", rating: 5, featured: 0, sortOrder: 43 },
    { name: "Dr. Bhavna Gupta", designation: "Associate Professor", university: "Maharaja Sayajirao University", contentEn: "AcademicHelp's journal selection service saved me months of trial and error. They matched my paper with the perfect target journal on the first attempt.", contentHi: "AcademicHelp की जर्नल चयन सेवा ने मुझे महीनों के ट्रायल एंड एरर से बचाया। उन्होंने पहले प्रयास में ही मेरे पेपर को सही लक्ष्य जर्नल से मैच किया।", rating: 5, featured: 0, sortOrder: 44 },
    { name: "Dr. Pradeep Nair", designation: "Assistant Professor", university: "NIT Surathkal", contentEn: "Their expertise in engineering research publication is unparalleled. They helped me navigate the complex requirements of IEEE and Elsevier journals.", contentHi: "इंजीनियरिंग शोध प्रकाशन में उनकी विशेषज्ञता बेजोड़ है। उन्होंने मुझे IEEE और Elsevier जर्नल की जटिल आवश्यकताओं को नेविगेट करने में मदद की।", rating: 5, featured: 0, sortOrder: 45 },
    { name: "Dr. Madhuri Dixit", designation: "Professor", university: "SNDT Women's University", contentEn: "The quality of their academic writing service is remarkable. They maintain scholarly tone while ensuring clarity and readability.", contentHi: "उनकी अकादमिक लेखन सेवा की गुणवत्ता उल्लेखनीय है। वे स्पष्टता और पठनीयता सुनिश्चित करते हुए विद्वतापूर्ण स्वर बनाए रखते हैं।", rating: 5, featured: 0, sortOrder: 46 },
    { name: "Dr. Suresh Pillai", designation: "Head of Department", university: "CUSAT Kochi", contentEn: "AcademicHelp has been instrumental in transforming our department's research culture. Their training and support services are exceptional.", contentHi: "AcademicHelp हमारे विभाग के शोध संस्करण को बदलने में अहम रहा है। उनकी प्रशिक्षण और सहायता सेवाएं असाधारण हैं।", rating: 5, featured: 0, sortOrder: 47 },
    { name: "Dr. Kusum Sharma", designation: "Research Scholar", university: "Central University of Rajasthan", contentEn: "Their guidance on choosing between qualitative and quantitative approaches was invaluable. They helped me design a perfect mixed-methods study.", contentHi: "गुणात्मक और मात्रात्मक दृष्टिकोणों के बीच चुनने पर उनका मार्गदर्शन अमूल्य था। उन्होंने मुझे एक परिपूर्ण मिश्रित-विधि अध्ययन डिज़ाइन करने में मदद की।", rating: 5, featured: 0, sortOrder: 48 },
    { name: "Dr. Hemant Chaturvedi", designation: "Associate Professor", university: "MNNIT Allahabad", contentEn: "The citation analysis and bibliometric service provided deep insights into research trends. Their VOSviewer expertise is truly world-class.", contentHi: "उद्धरण विश्लेषण और बिब्लियोमेट्रिक सेवा ने शोध रुझानों में गहन अंतर्दृष्टि प्रदान की। उनकी VOSviewer विशेषज्ञता वास्तव में विश्व-स्तरीय है।", rating: 5, featured: 0, sortOrder: 49 },
    { name: "Dr. Sujatha Ramesh", designation: "Assistant Professor", university: "Bharathiar University", contentEn: "Their AI tools training workshop transformed how I approach literature reviews. I can now complete reviews in half the time with better quality.", contentHi: "उनकी AI टूल्स ट्रेनिंग वर्कशॉप ने मेरे साहित्य समीक्षा के दृष्टिकोण को बदल दिया। मैं अब बेहतर गुणवत्ता के साथ आधे समय में समीक्षा पूरी कर सकती हूं।", rating: 5, featured: 0, sortOrder: 50 },
    { name: "Dr. Lokesh Agarwal", designation: "Professor", university: "Devi Ahilya University", contentEn: "Exceptional PhD thesis support from proposal to final submission. Their chapter-wise guidance was structured and comprehensive.", contentHi: "प्रस्ताव से लेकर अंतिम सबमिशन तक असाधारण पीएचडी थीसिस सहायता। उनका अध्याय-वार मार्गदर्शन संरचित और व्यापक था।", rating: 5, featured: 0, sortOrder: 51 },
    { name: "Dr. Pallavi Ghosh", designation: "Research Fellow", university: "Presidency University Kolkata", contentEn: "Their support in getting my economics paper published in a Q1 journal was phenomenal. The methodology chapter they refined was particularly impressive.", contentHi: "Q1 जर्नल में मेरे इकोनॉमिक्स पेपर को प्रकाशित करने में उनकी सहायता असाधारण थी। उन्होंने रिफाइन की मेथडोलॉजी चैप्टर विशेष रूप से प्रभावशाली थी।", rating: 5, featured: 0, sortOrder: 52 },
    { name: "Dr. Vinayak Hegde", designation: "Associate Professor", university: "Manipal Academy of Higher Education", contentEn: "AcademicHelp's systematic review training enhanced my research capabilities significantly. I can now independently conduct high-quality reviews.", contentHi: "AcademicHelp की सिस्टमैटिक रिव्यू ट्रेनिंग ने मेरी शोध क्षमताओं को significant रूप से बढ़ाया। मैं अब स्वतंत्र रूप से उच्च-गुणवत्ता वाली समीक्षाएं Conduct कर सकता हूं।", rating: 5, featured: 0, sortOrder: 53 },
    { name: "Dr. Nandini Krishnamurthy", designation: "Assistant Professor", university: "Christ University Bangalore", contentEn: "Their publication support team is responsive, professional, and deeply knowledgeable about journal requirements across disciplines.", contentHi: "उनकी प्रकाशन सहायता टीम उत्तरदायी, पेशेवर और विभिन्न विषयों में जर्नल आवश्यकताओं के बारे में गहन रूप से जानकार है।", rating: 5, featured: 0, sortOrder: 54 },
    { name: "Dr. Prashant Dubey", designation: "Professor", university: "Rajiv Gandhi Proudyogiki Vishwavidyalaya", contentEn: "The research paper they helped me write on AI applications in education got accepted in a top Scopus journal. Their interdisciplinary expertise is remarkable.", contentHi: "शिक्षा में AI अनुप्रयोगों पर उनकी मदद से लिखा गया रिसर्च पेपर एक शीर्ष Scopus जर्नल में स्वीकार हो गया। उनकी अंतःविषय विशेषज्ञता उल्लेखनीय है।", rating: 5, featured: 0, sortOrder: 55 },
    { name: "Dr. Kiran Bedi", designation: "Research Scholar", university: "IIT Jodhpur", contentEn: "Their confidentiality and ethical approach to research support gave me complete peace of mind. A truly trustworthy academic partner.", contentHi: "शोध सहायता के लिए उनकी गोपनीयता और नैतिक दृष्टिकोण ने मुझे पूरी तरह से मन की शांति दी। एक वास्तव में trustworthy अकादमिक साझेदार।", rating: 5, featured: 0, sortOrder: 56 },
  ]);
  console.log("Testimonials seeded.");
  console.log("Seed complete!");
}

seed().catch(console.error);
